name: Pre-Merge

on:
  pull_request:
    branches:
      - '**'

jobs:
  assemble:
    name: Assemble the outputs of this project (Fast check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: run assemble
        run: ./gradlew assemble

  ktlint:
    name: Check code style with Ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Check ktlint
        run: ./gradlew ktlintCheck
