name: Pre-Merge

on:
  pull_request:
    branches:
      - '**'

jobs:
  assemble:
    name: Assemble Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Android app
        run: |
          ./gradlew --scan --stacktrace \
            assembleDebug \
            androidApp:lintDebug

  test:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Unit test
        run: |
          ./gradlew --scan --stacktrace \
            testDebugUnitTest

  iOS:
    name: Assemble iOS framework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Assemble iOS framework
        run: |
          ./gradlew --scan --stacktrace \
            linkDebugFrameworkIosX64

  ktlint:
    name: Check Android code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Check ktlint
        run: ./gradlew ktlintCheck
