name: Dependency Updates

on:
  schedule:
    # Run at every Saturday 0:0 UTC.
    - cron: "0 0 * * SAT"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates
